language: generic
sudo: false

matrix:
  fast_finish: true
  include:
    - env: BUILD=cabal CABALVER=1.24 GHCVER=8.0.2
      compiler: ": #GHC 8.0.2"
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.2], sources: [hvr-ghc]}}

script:
  - cabal configure --enable-tests && cabal build && cabal test
